### ISSUE TITLE
Not all Vertices Printed When District is Split

### ISSUE THREAD

**Issue by rishabco** [tylersco/Scott_Vienneau_CSCI2270_FinalProject#2]
So when the districts are split up, none of the options under "Print Vertices" allow you to see all of the districts. I tried going through and basically deleted the vertices  between Eiffel Tower and  Taj Mahal to make multiple districts (Deleted "Great Wall of China" and "Giza Pyramids"). Unfortunately, when I went back to print out the vertices, it would only print out the vertices in the district of the starting city. Perhaps there is a way to print out all of the districts, or just print out all of the vertices stored in the graph along with their district ID?

**Comment by tylersco** [comment]
I have a displayEdges method which will display all edges and vertices, it does not matter on the district. The reason the print methods work this way is because the breadth-first and depth-first search traversals only find connected components and if there are two districts, the methods will only print the vertices connected to the starting landmark parameter.
